name: Azure OpenAI Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Setup Go modules and dependencies
        run: |
          # Create a temporary directory for the script and initialize Go module
          mkdir -p ./.github/workflows/scripts/temp
          cd ./.github/workflows/scripts/temp
          go mod init azure-openai-test
          
          # Copy the script to the temp directory
          cp ../*.go ./
          
          go get github.com/Azure/azure-sdk-for-go/sdk/ai/azopenai
          go get github.com/Azure/azure-sdk-for-go/sdk/azcore/to
            
      - name: Run
        run: |
          cd ./.github/workflows/scripts/temp
          go run azure_openai_hello.go
        env:
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
