name: Java Test Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Generate AI-friendly repository structure
      run: |
        # Install tree command and jq
        sudo apt-get install -y tree jq
        
        # Create a traditional tree view for human reading
        echo "Repository structure:" > repo-structure.txt
        tree -a -I '.git' >> repo-structure.txt
        
        # Generate clean hierarchical JSON structure
        tree -a -I '.git' -J | jq '[.[0] | {name: "repository", contents: [recurse(.contents[]? | {name: .name, type: .type, contents: .contents})] | sort_by(.name)}][0]' > repo-structure.json
        
        # Display the structure
        cat repo-structure.txt
        echo "JSON structure available at: repo-structure.json"
        
    - name: Upload repository structure
      uses: actions/upload-artifact@v4
      with:
        name: repo-structure
        path: |
          repo-structure.json
          repo-structure.txt
          
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
          
    - name: Send hello world to Azure OpenAI
      env:
        AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      run: |
        # Run the Go script from the repository
        go run .github/workflows/scripts/azure_openai_hello.go
        
    - name: Upload Azure OpenAI response
      uses: actions/upload-artifact@v4
      with:
        name: azure-openai-response
        path: azure_openai_response.txt