name: Java Test Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Generate AI-friendly repository structure
      run: |
        # Install tree command
        sudo apt-get install -y tree
        
        # Check tree version
        tree --version
        
        # Create a traditional tree view for human reading
        echo "Repository structure:" > repo-structure.txt
        tree -a -I '.git' >> repo-structure.txt
        
        # Generate JSON structure using tree's built-in JSON option (-J)
        tree -a -I '.git' -J > repo-structure.json
        
        # Display the structure
        cat repo-structure.txt
        echo "JSON structure available at: repo-structure.json"
        
    - name: Upload repository structure
      uses: actions/upload-artifact@v4
      with:
        name: repo-structure
        path: |
          repo-structure.json
          repo-structure.txt